### ISSUE TITLE
Error get context user

### ISSUE THREAD

**Issue by tommoholmes** [saleor/saleor#10243]
### What I'm trying to achieve
I want to get user context info

### Steps to reproduce the problem
I Access query and add some print method 
in ss

```
mutation {
  productDelete(id: "UHJvZHVjdDoy") {
    errors {
      field
      message
      code
      attributes
      values
    }
    product {
      id
      seoTitle
      seoDescription
      name
      description
      slug
      created
      updatedAt
      chargeTaxes
      rating
      channel
      availableForPurchaseAt
      isAvailableForPurchase
    }
  }
}
```

### What I expected to happen
`AnonymousUser`

### Screenshots and logs

![Screen Shot 2022-07-26 at 18 10 33](https://user-images.githubusercontent.com/12724592/180993314-e7f93b19-e9e9-42a3-bf9a-50440e0219ba.png)

**System information**
<!-- Provide the version
branch `main`

Operating system:
- [ ] Windows
- [ ] Linux
- [ V] MacOS
- [ ] Other

**Comment by peelar** [comment]
Hello @tommoholmes, thanks for reaching out 👋.

In order to help you, we must be able to see the error which is not possible right now due to a cropped screenshot you attached.

Also, please update the "steps to reproduce" section to contain everything you did before running the query, what are the details of your environment, and what you expected to happen.

Only given those details we might be able to help you. Thanks!

**Comment by tommoholmes** [comment]
that issue is, in mutation product.py, when I try to get `info.context.user` I got message anonymousUser that mean is My user is `Guest`

**Comment by peelar** [comment]
Thank you for your answer @tommoholmes.

To find the cause of your issue, we still need some more information. Please provide:
- the steps to reproduce - instructions on what we have to do to see the exact error you have
- system information - what version of Saleor are you running? Is it modified? 

Only then we are able to help you.

Have a nice day 🌻
