### ISSUE TITLE
[RFC] Bulk update mutations

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor#10798]
Sometimes we need to change or create multiple objects at once. The most common scenario for that is changing either multiple variants or products while calling that sort of update one by one is really ineffective. This feature will unlock us with building more sophisticated user experiences such as data-grid management / inline editing.

## General assumptions
- Priority is to implement bulk operations for everything related to the product: product itself, variants, prices, metadata
- New mutations:
  - `productBulkCreate` - creating new products
  - `productBulkUpdate` - updating existing products
  - `productVariantBulkCreate` - creating new variants
  - `productVariantBulkUpdate` - updating existing variants
  - `metadataBulkUpdate` - updating metadata
- Policies of error handling/validation
  - `IGNORE_FAILED` - save whatever you can, don't reject anything, including errors, and return objects that were saved
  - `REJECT_FAILED_ROWS` - reject rows with errors
  - `REJECT_EVERYTHING` - reject everything if at least one object is invalid - `default option`
- Error handling on two levels (see examples)
  - Ordinary Graphql-spec-based errors: A field `errors` next to `data` that contains general errors for all rows
  - Row-level-based `errors` field that belongs to the certain input

### New error policies
```graphql
enum ErrorPolicyEnum {
  # Save what is possible within a single row. If there are errors in an input data row, try to save it partially and skip the invalid part.
  IGNORE_FAILED
  # Reject rows with errors.
  REJECT_FAILED_ROWS
  # Reject all rows if there is at least one error in any of them
  REJECT_EVERYTHING
}
```

### Product variant changes
- Update `productVariantBulkCreate` mutation with `errorPolicy`, handle different error policies in the mutation
- Update `ProductVariantBulkCreate`:
  - deprecate `productVariants`
  - add `results` 
  - add `ProductVariantBulkCreateResult`
- Add `productVariantBulkUpdate` mutation
- Add `ProductVariantBulkUpdateInput` -  use the same fields as in `ProductVariantBulkCreateInput` but with variant `id`

```graphql
input ProductVariantBulkUpdateInput{
  id: ID!
  attributes: [BulkAttributeValueInput!]!
  sku: String
  name: String
  externalReference: String
  trackInventory: Boolean
  weight: WeightScalar
  preorder: PreorderSettingsInput
  quantityLimitPerCustomer: Int
  stocks: [StockInput!]
  channelListings: [ProductVariantChannelListingAddInput!]
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
}

type ProductVariantBulkCreate {
  count: Int!
  productVariants: [ProductVariant!]! @deprecated(reason: "This field will be removed in Saleor 4.0. Use `errors` field instead.")
  bulkProductErrors: [BulkProductError!]! @deprecated(reason: "This field will be removed in Saleor 4.0. Use `errors` field instead.")
  errors: [BulkProductError!]! @deprecated(reason: "This field will be removed in Saleor 4.0. Use `errors` field instead.")
  results: [ProductVariantBulkResult!]!
}

type ProductVariantBulkUpdate {
  count: Int!
  results: [ProductVariantBulkResult!]!
}

type ProductVariantBulkResult {
  productVariant: ProductVariant
  errors: [ProductVariantBulkError!]!
}

type ProductVariantBulkError {
  field: String
  message: String
  code: ProductErrorCode!
  attributes: [ID!]
  values: [ID!]
  warehouses: [ID!]
  channels: [ID!]
}

type Mutation {
  # Variant create (existing)
  productVariantBulkCreate(
    product: ID!, variants: [ProductVariantBulkCreateInput!]!, errorPolicy: ErrorPolicy
  ): ProductVariantBulkCreate

  # Variant update
  productVariantBulkUpdate(
     product: ID!, variants: [ProductVariantBulkUpdateInput!]!, errorPolicy: ErrorPolicy
  ): ProductVariantBulkUpdate
}
```

### Product changes
- Add `productBulkCreate` mutation
- Add `productBulkUpdate` mutation

```graphql
input ProductBulkCreateInput {
  attributes: [AttributeValueInput!]
  category: ID
  chargeTaxes: Boolean
  collections: [ID!]
  description: JSONString
  name: String
  slug: String
  taxCode: String
  seo: SeoInput
  weight: WeightScalar
  rating: Float
  productType: ID!
  channelListings: [ProductChannelListingCreateInput!]
  media: [MediaInput!]
  variants: [ProductVariantBulkCreateInput!]!
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
}

input ProductBulkUpdateInput {
  id: ID!
  attributes: [AttributeValueInput!]
  category: ID
  chargeTaxes: Boolean
  collections: [ID!]
  description: JSONString
  name: String
  slug: String
  taxCode: String
  seo: SeoInput
  weight: WeightScalar
  rating: Float
  channelListing: ProductChannelListingUpdateInput
  addMedia: [MediaInput!]
  removeMedia: [ID!]
  variants: [ProductVariantBulkUpdateInput!]
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
}

type MediaInput {
  alt: String
  image: Upload
  mediaUrl: String
}

type ProductBulkCreate {
  count: Int!
  results: [ProductBulkResult!]!
}

type ProductBulkUpdate {
  count: Int!
  results: [ProductBulkResult!]!
}

type ProductBulkResult {
  product: Product
  errors: [ProductBulkError!]!
}

type ProductBulkError {
  field: String
  message: String
  code: ProductErrorCode!
  attributes: [ID!]
  values: [ID!]
  warehouses: [ID!]
  channels: [ID!]
}

type Mutation {
  # Product create / update
  productBulkCreate(products: [ProductBulkCreateInput!]!, errorPolicy: ErrorPolicy): ProductBulkCreate
  productBulkUpdate(products: [ProductBulkUpdateInput!]!, errorPolicy: ErrorPolicy): ProductBulkUpdate
}
```

### Metadata changes
- Add `metadataBulkUpdate` mutation for updating metadata in bulk
- The `metadataBulkUpdate` should require the object `ids` of the same type, if the different data types will be provided the error will be raised
```graphql
input MetadataBulkUpdateInput {
  # ID or token (for Order and Checkout) of an object to update.
  id: ID!
  # Fields required to update the objects metadata.
  metadata: [MetadataInput!]!
}

type MetadataBulkUpdate {
  count: Int!
  results: [MetadataBulkUpdateResult!]!
}

type MetadataBulkUpdateResult {
  item: ObjectWithMetadata!
  errors: [MetadataBulkError!]!
}

type MetadataBulkError {
  field: String
  message: String
  code: MetadataErrorCode!
}

type Mutation {
  # Metadata update
  metadataBulkUpdate(input: [MetadataBulkUpdateInput]!!, errorPolicy: ErrorPolicy): MetadataBulkUpdate
}
```

### Create products with errors
```graphql
mutation {
  productBulkCreate(input: [{...}, {...}]) {
    count
    results {
      product {
        id
        name
      }
      errors {
        field
        code
      }
    }
  }
}
```
response:
```json
{
  "data": {
    "productBulkCreate": {
      "count": 1,
      "results": [
        {
          "product": {
            "id": "...",
            "name": "...."
          },
          "errors": [
            {
              "field": "...",
              "code": "..."
            }
          ]
        }
      ]
    }
  },
  "error": [
    {
      "message": "...",
      "location": "..."
    }
  ]
}
```

**Comment by patrys** [comment]
I think the mutation is supposed to say:

```graphql
mutation {
  productBulkCreate(input: [{...}, {...}]) {
    products {
      product {
        id
        name
      }
      errors {
        field
        code
      }
    }
  }
}
```

**Comment by andrzejewsky** [comment]
yeah @patrys you are right, fixed

**Comment by SzymJ** [comment]
Update:
Example inputs were updated - `ProductVariantBulkCreateInput`, `ProductVariantBulkUpdateInput`, `ProductBulkCreateInput`, `ProductBulkUpdateInput` accepting `metadata: [MetadataInput!]` and
 ` privateMetadata: [MetadataInput!]`

In `ProductBulkCreateInput` `channelListings` has been changed from `ProductChannelListingAddInput` to new `ProductChannelListingCreateInput` that does not contain fields that won't be used during create and fields that are deprecated but still are available in `ProductChannelListingAddInput`.

**Comment by SzymJ** [comment]
More detailed info about `Error handling on two levels`:

Currently, on the existing `productVariantBulkCreate` mutation all errors are returned on the `data` level which is bad behavior. All errors related to data should be returned on the `row` level in `ProductVariantBulkResult` or `ProductBulkResult`. If for example the variant is not created because of some errors `ProductVariantBulkResult` should return 
```
{
  "productVariant": null,
  "errors": [{...}, {...}]
}
```

**Comment by maarcingebala** [comment]
Note: `ProductBulkCreateInput.taxCode` and `ProductBulkUpdateInput.taxCode` input fields are deprecated, instead `taxClass: ID` should be added.

**Comment by ivanakcheurov** [comment]
Excellent ticket!

A couple of ideas that would make migrations and data synchronizations easier:

### Idempotence
1) It is convenient to be able to make mutations (batch or single) as **idempotent**. 
_Example_: one of batch mutations may require to Create a Product X with specific data and attributes. But in the meantime some stuff member has already done that manually. Therefore the batch mutation returns success (as a bonus: the mutation could also report back that the product X had already existed prior).
Same with deletions and updates -> if the data is already in the desired state, then return success.

### Upserts
Right now I need to query everything beforehand to know if creation makes sense or not, Then if the product is already there, I need to do a manual diff. If there are differences between actual and desired state of the product, I do update.
I would rather make a bunch of upserts when synchronizing all products from our ERP to Saleor.

### A product with multiple variants is split into 2 separate products
Similarly we need sometimes to combine 2 products with different variants into 1 product containing all those variants.
The problem with these 2 mutations is that I cannot delete a product variant to recreate it inside another product because if this product variant was in somebody's purchase history, then it would disappear from the purchase history upon delete->create operation.

### Reordering 

### Edge case with simultaneous increments 
3) Batch updates are async and therefore may require **race-condition-proof increments/decrements**.
_Example_: Saleor is used as a stock management source of truth. An external system wants to decrease stock value for SKU X by 1.
Optimistic concurrency: 
_Request 1_ "change stock value for SKU X from 10 to 9" When Saleor executes the mutation, it checks the current stock value which found to be 8 (perhaps of another concurrent decrement having taken place). It returns _error_ "should have updated stock value from 10 to 9 but value of 8 was found. Please update your request".
_Request 2_ "change stock value for SKU X from 8 to 7" When the mutation gets executed, it checks the current stock value which found to be 8. The mutation sets the stock value as 7 and returns _success_.

**Comment by maarcingebala** [comment]
Closing this ticket as most of these mutations are now delivered, we'll open separate tickets to track any new ones or changes to them.
