### ISSUE TITLE
[RFC] Webhooks dry run

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#11456]
We want to improve the experience of building and using webhooks, by giving the ability to:
- dry run webhook events for testing purposes
- run webhook events manually with an actual delivery

Below is the proposed scope of changes.

## 1. Dry run webhook events

Add a mutation that performs a dry run of a webhook event. Mutation should accept subscription query and an object ID to serialize. As a result it should return a JSON response with serialized data, based on given subscription query. Reuse functions that are already used by subscription webhooks to generate payload.

- Add validation to check if given object ID matches the event, e.g. `OrderCreated` event requires an order ID and should fail if other ID is provided.
- Perform the dry-run in the context of currently logged in staff user.

### Schema

```graphql
type Mutation {
  """Performs a dry run of a webhook event."""
  webhookDryRun(query: String!, objectId: ID!): WebhookDryRun
}

type WebhookDryRun {
  errors: [WebhookDryRunError!]!
  """JSON payload that would be sent out to webhook's target URL."""
  payload: JSONString
}

type WebhookDryRunError {
  field: String
  code: WebhookDryRunErrorCode!
}

enum WebhookDryRunErrorCode {
  """Triggered when object ID doesn't match with the event type."""
  INVALID_ID
}
```

Example:

```graphql
mutation {
  webhookDryRun(
    objectId: "UHJvZHVjdDoxNTI=",
    query: "subscription { event { ... on ProductUpdated { product { id name description } } } }"
    ) {
      errors {
        field
        code
        message
      }
      payload
    }
}
```

Note: Dry run should be support only for subscription webhooks.

## 2. Trigger webhook events manually

Add a mutation that allows to trigger and deliver a webhook for given object ID. 

### Schema

```graphql
type Mutation {
  """Trigger a webhook event."""
  webhookTrigger(webhookId: ID!, objectId: ID!): WebhookTrigger
}

type WebhookTrigger {
  errors: [WebhookTriggerError!]!
  delivery: EventDelivery
}

type WebhookTriggerError {
  field: String
  message: String
  code: WebhookTriggerErrorCode!
}

enum WebhookTriggerErrorCode {
  """Triggered when object ID doesn't match with the event type."""
  INVALID_ID
}
```

Example:

```graphql
mutation {
  webhookTrigger(webhookId: "V2ViaG9vazox", objectId: "UHJvZHVjdDoxNTI=") {
    errors {
      field
      code
      message
    }
    delivery {
      id
      status
      eventType
    }
  }
}
```

## 3. Extract webhook event from the subcription query

Current API for creating and updating subscription webhooks has redundat arguments: `asyncEvents` or `syncEvents` which could be omitted whenever the `query` parameter is provided. Consider this example from the current API:

```graphql
mutation {
  webhookCreate(input: {
    name: ""
    targetUrl: ""
    asyncEvents: [ORDER_CREATED],
    query: "subscription { event { ... on OrderCreated { order { number } } } }"
  }) {
    webhook {
      id
    }
  }
}
```

Given the following subscription query:
```graphql
subscription { event { ... on OrderCreated { order { number } } } }
```
The event being subscribed is `OrderCreated` and the mutation also needs `asyncEvents: [ORDER_CREATED]` to properly create a webhook. This is redundant, as the webhook event could be extracted from the subscription query. 

### Proposed changes

Do not require passing `asyncEvents` or `syncEvents` parametrs when the `query` is provided. Example of how new API should work:

```graphql
mutation {
  webhookCreate(input: {
    name: ""
    targetUrl: ""
    query: "subscription { event { ... on OrderCreated { order { number } } } }"
  }) {
    webhook {
      id
    }
  }
}
```

When the `query` parameter is provided, use it to extract the webhook event.

**Comment by IKarbowiak** [comment]
LGTM 🎉

**Comment by korycins** [comment]
> Do not require passing asyncEvents or syncEvents parametrs when the query is provided.

We should take into account here, that developers can use fragments, or provide the fragments that are not included in the subscription query. Maybe an edge case, but I think that at least we should keep in mind this. Something like this:
```graphql
fragment NotUsedEvents on Event {
  ... on OrderCreated {
    order {
      id
    }
  }
}

subscription {
  event {
    ... on OrderUpdated {
      order {
        id
      }
    }
  }
}
```

---

Also, some webhooks send data that is not stored in the DB, but the payload is built based on the customer input. 
For example payment webhooks send paymentData object (currently it works for old payloads but this part is missing for subscription), or TransactionActionRequest sends the amount and type of action requested by user. 

---
```graphql
type Mutation {
  webhookTrigger(input: WebhookTriggerInput!): WebhookTrigger
}

input WebhookTriggerInput {
  """The ID of an object to serialize."""
  id: ID!

  """The subscription query that defines the webhook event and its payload."""
  query: String!
}

type WebhookTrigger {
  errors: [WebhookTriggerError!]!
  delivery: EventDelivery
}
```
Shouldn't we also accept the `webhookId` here? Currently, you pass here an `id` of the object to serialize and the `query`, but you don't provide the details, of where this webhook should be sent.
Also by using already existing webhook you can also confirm that your webhook config is correct, and everything for this webhook works as expected (for example, you don't have issue with permissions).

The next plus of this approach: EventDelivery is stricty related to the `Webhook` type (on graphql lvl, and DB lvl). So providing already existing webhook should reduce an amount of work for us.

---

```graphql
enum WebhookTriggerErrorCode {
  """Triggered when object ID doesn't match with the event type."""
  INVALID_ID
}
```
Only an idea, but maybe we could add something like `MISSING_APP_PERMISSION` or something and raise it when we can't build a payload because of missing permission?

**Comment by maarcingebala** [comment]
Thanks for the feedback @korycins! 
- Good point about missing `webhookId` - yes it's obviously required to know which webhook object to use.
- We'll see how discovering the event type works with fragments, but I think we should be able to precisely parse the query tree to get the actual event names.
- About the errors - we will take it into account, I'm not yet sure what possible errors we will be returning there so the list is likely going to be extended.

**Comment by maarcingebala** [comment]
@korycins Fixed the schema with `id: ID!` which is the webhook ID.
