### ISSUE TITLE
Use replica database connections in all resolvers when applicable

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#11547]
### What I'm trying to achieve
When a read-only query is sent to the GraphQL backend (i.e. not a mutation), all resolvers should use the replica database connection rather than the default one.

Example of resolvers not using the adequate database connection: https://github.com/saleor/saleor/blob/9e45fc88aacc86271e757adb464fdc3297999f39/saleor/graphql/discount/types.py#L136-L147

### Describe a proposed solution
In all resolvers use the replica connection if read-only.

### Other solutions I've tried and won't work
N/A

### Screenshots or mockups

N/A

**Comment by maarcingebala** [comment]
As part of this issue, we should do the following:
- identify all DB calls that use writer when reading and fix them,
- see if we can add a workflow that will prevent this issue in the future e.g. by using `semgrep`:
  - e.g. think of forcing `.objects.using()` so that we explicitly define reader/writer

**Comment by tomaszszymanski129** [comment]
Sempgrep rules will be handled in a separate task https://github.com/orgs/saleor/projects/16/views/13?pane=issue&itemId=44261396
