### ISSUE TITLE
Allow to create Order with arbitrary product lines 

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#11720]
### What I'm trying to achieve

I want to create integration that imports orders from another commerce engine to Saleor.

I assume orders are already fulfilled or "archived" at some point (I don't modify them, I only transfer the history)

At the moment Order require relation to actual products (and probably - actual customer). These products don't exist, since they are not migrated/don't exist in Saleor (yet, or never will be).

### Describe a proposed solution
Either:
1. Create a separate entity like ArchivedOrder which will be the final status of existing order + allow to create such order with the API, where all products, customers etc can be created with mutation input (deep, not relations)
2. Extend existing API to allow creating orders with arbitrary lines and customers, probably with "fulfilled" status (or some extra status, to avoid invalid states).
3. ... or other solution I don't know about

It'd be great if this also comes with a bulk creation API

**Comment by maarcingebala** [comment]
The [bulkOrderCreate](https://docs.saleor.io/docs/3.x/developer/bulks/bulk-orders) mutation should work in this case, the only thing we would need to change is not requiring a valid variant ID. In Saleor orders and their lines can exist without matching variants in the database, but this mutation requires that. Since this is still a Feature Preview, we could change that.
