### ISSUE TITLE
Standalone plugin/gateway for PayPal without Braintree

### ISSUE THREAD

**Issue by vetemi** [saleor/saleor#12042]
### What I'm trying to achieve 
Have standalone plugin for PayPal as payment gateway. As far as I understood Braintree is the only plugin provided for PayPal. I saw a couple of issues regarding PayPal but somehow every attempt was not successful or is very old ([#2467](https://github.com/saleor/saleor/issues/2467), [#5577](https://github.com/saleor/saleor/pull/5577), etc.). 

### Describe a proposed solution
It would be nice to have a PayPal integration without Braintree. If this is not on your roadmap for the next couple of weeks, it would be very helpful if you can provide me resources on how to create a PayPal Plugin on my own. Also, it would be helpful to understand why you abandoned this feature for so long as I assume it's a major issue for many people.

### Other solutions I've tried and won't work
The problem is that it's almost impossible to create a Braintree production account, at least for a German located business. I talked to multiple sales and support people and everyone stated that Braintree is not suitable. 

Any help, resource or at least statement would be very helpful. Thank you guys! <3

**Comment by korycins** [comment]
Hey @vetemi ,

I believe that you can also use paypal by using  Adyen plugin: https://docs.saleor.io/docs/3.x/developer/available-plugins/adyen
Available payment methods with Adyen: https://www.adyen.com/payment-methods

>  If this is not on your roadmap for the next couple of weeks, it would be very helpful if you can provide me resources on how to create a PayPal Plugin on my own.

I would suggest building a payment app instead of the payment plugin. The difference between them is that the payment app is a separate service that communicates via webhook & API, where the plugin is embedded python code inside the saleor core.
More about SaleorApps and Plugins: https://docs.saleor.io/docs/3.x/developer/extending/overview

In Saleor3.4 we introduced the API that allows you to create the orders by Saleor App: https://docs.saleor.io/docs/3.x/developer/checkout#finalizing-checkout-with-saleor-app
We are still improving them to give a better way of handling the payment. Here you can see a PR with the updated docs and changes that should be released in 3.12 - https://github.com/saleor/saleor-docs/pull/659

The next step is to provide fully replacement of the current payment plugin flow. The all details related to this one can be found here: https://github.com/saleor/saleor/issues/11258. We don't have ETA for this part, but I am already working on this. 

Also, keep in mind that TransactionAPI  is a preview feature, so some breaking changes could be applied there (You will still have time to fix your app, but instead of waiting to release Saleor4.0 to remove the deprecated fields, we will remove them in next release).

**Comment by patrys** [comment]
I think this is best reported as a discussion under https://github.com/saleor/apps
