### ISSUE TITLE
can we a add a new end point(post request) in existing saleor app?

### ISSUE THREAD

**Issue by RZ-Jyothsna** [saleor/saleor#12368]
I am trying to add new api endpoint in saleor backend. Through this I need to hit some third party api. Is it possible?

This is the data I could see in localhost, if i run my api.

`GET /api/`

`HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
   all api routes
}`

**Comment by timuric** [comment]
Hey @RZ-Jyothsna Saleor is not designed to be a backend framework, we discourage forking Saleor as this leads to big maintenance burden. Best way to use Saleor is microservice approach and commincate/extend using only GraphQL

**Comment by alperenkaplan** [comment]
I am sorry for reopening the issue but people will probably find this issue in the future and I just wanted to add to @timuric and warn you about going down this road. 

I am not part of the Saleor/Mirumee team and I have been using Saleor for some time now. I have forked the project like 2 years ago and I have been extending the project adding new queries, mutations, new features etc. Whatever I need. 

I was like "How much work can it be? This is an open-source project. Open-source projects are meant to be forked and used as you wish" in the beginning. Oh boy was I wrong. You don't fully understand how big of a project this is and how fast it is changing, how fast it is growing before you start to work on it. Once you fork it, you need to maintain it yourself, you are on your own. You need to keep yourself updated on the main project since there are fixes, new features and updates all the time. While doing this, you are going to carefully merge the changes in the saleor repo to yours without overriding your changes. I feel like I am not being clear enough how much work that is, while also developing other features for your own repo.

I know you just want to add one small endpoint to your project, which in theory is pretty easy. However, when you fork and make changes, you will have conflicts and and can't get remote changes that easily.

Just don't do it people. Write custom apps. I know there are some features you would like to see on the project. If you want to have those features, create pull requests instead of going down my road. If the feature you wrote is something that an e-commerce platform needs, devs will probably merge it into the repo, then you can pull the main repo.
