### ISSUE TITLE
Bug: Apps can't get full payloads for sync webhooks

### ISSUE THREAD

**Issue by binary-koan** [saleor/saleor#12559]
### What are you trying to achieve?

Trying to create an app which registers sync payment/shipping webhooks automatically via the manifest.

### Steps to reproduce the problem

1. Create an app project
2. Add a webhook like the following to the manifest
```
{
  name: "Payment: List Gateways",
  syncEvents: ["PAYMENT_LIST_GATEWAYS"],
  targetUrl: "...",
  isActive: true
}
```
3. Attempt to add the app to a Saleor instance
4. This results in an error: "Missing required fields for webhook: query"

Specifying query as null or an empty string also fails.

The only way to get the app to register is to set query to valid GraphQL, e.g. `"subscription { event { issuedAt } }"`

### What did you expect to happen?

This causes problems because (as far as I can tell) not all information in the default sync webhook payloads is available in the GraphQL subscription payload.

I expected that query would only be required for `asyncEvents`, not `syncEvents`.

(When adding a webhook in the UI, there's no option to add a `query` for sync webhooks, so I assume the non-subscription version is what's meant to be used)

### Environment

Saleor version: main (`7465cc83b`)
OS and version: Docker 4.10.1 on macOS

**Comment by maarcingebala** [comment]
Hey, we want all webhooks to rely on GraphQL subscriptions, also the sync ones. Can you specify what fields are missing in the GraphQL subscription payload? Regarding the UI, you should be able to provide subscription queries for sync webhooks:
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/5421321/232416296-76606010-9893-49ec-bb4a-3acd31e1fadb.png">

**Comment by binary-koan** [comment]
@maarcingebala Ah OK. Rather than shipping events, I was looking at payment ones and couldn't find a way to get the `data` (i.e. what's passed as `paymentData` in `checkoutComplete`) from the `PaymentProcessEvent` payload?

I can see a lot of things are starting to use `transaction` though, so maybe I'm on the wrong track in general and shouldn't be relying on `paymentData` anyway?

For the UI I was on the wrong branch on the dashboard project so was still seeing an old UI which disabled the input for sync events, my bad.

**Comment by korycins** [comment]
Hey @binary-koan , You're right. Some of the data in the static payload is not included in the GraphQL subscription.

If you're building an integration with a payment provider, I suggest using the newest `transactionAPI` that was introduced in 3.13. It replaces the old payment plugin flow and is much more flexible. It allows you to do more than the payment webhook built based on the "old" payment plugin flow.

Here are a few highlighted differences between `transactionAPI` and the old payment flow:


  | TransactionAPI | PaymentPlugin (via Webhook)
-- | -- | --
Split payments. You can pay for the checkout with different payments | Yes | No
Can be used with checkout | Yes | Yes
Can be used with order (you can attach the payment to the existing order) | Yes | No
There is an interface that allows you to update the payment when it has been changed on the payment provider side (for example, someone made a charge/refund on the payment provider side) | Yes | No. You can process a payment, but there is no way to update a payment on the Saleor side when the update was triggered from the payment provider side
Tracking history | TransactionItem has events for each action that is sent to the App. Each event gets its own REQUEST_ event, and you can more easily track the history with this. The events are visible on the dashboard side. | Payment has a transaction that tracks the changes that have been made for the payment. It is not a perfect flow, as granularity is not very great
Providing feedback from processed payment | TransactionItem and TransactionEvent have fields like name or message. Both of them can be used to provide feedback related to the transaction or specific action that has been made. It will be visible on the dashboard side. | There are some fields that you can use to provide some info, but most of them are not visible on the dashboard, only from the API

Although the `transactionAPI` is a preview feature, based on the feedback gathered from the community, we could change the flow. We always try to provide a grace period to match the newest flow if it is possible.

Any feedback will be appreciated.

If you decide to check the `transactionAPI`:

- Docs for processing the payment with `transactionAPI`: [https://docs.saleor.io/docs/3.x/developer/payments#processing-a-payment-with-payment-app](https://docs.saleor.io/docs/3.x/developer/payments#processing-a-payment-with-payment-app)
- Docs for reporting the action for the transaction: [https://docs.saleor.io/docs/3.x/developer/payments#reporting-action-for-the-transaction](https://docs.saleor.io/docs/3.x/developer/payments#reporting-action-for-the-transaction)
- Docs for handling the action triggered on the Saleor side: [https://docs.saleor.io/docs/3.x/developer/payments#handling-the-action-triggered-on-saleor-side](https://docs.saleor.io/docs/3.x/developer/payments#handling-the-action-triggered-on-saleor-side)
- Explanation of how we handle the re-calculation: [https://docs.saleor.io/docs/3.x/developer/payments#re-calculations-of-transaction-amounts](https://docs.saleor.io/docs/3.x/developer/payments#re-calculations-of-transaction-amounts)
- Some diagrams showing how this can be used with the checkout: [https://docs.saleor.io/docs/3.x/developer/checkout#using-the-payment-app](https://docs.saleor.io/docs/3.x/developer/checkout#using-the-payment-app)
- Docs for AdyenApp (opensource), which can be used as an example: [https://docs.saleor.io/docs/3.x/developer/app-store/apps/adyen](https://docs.saleor.io/docs/3.x/developer/app-store/apps/adyen)

Keep in mind that when we'll have PaymentApps that cover the same payment providers as existing payment plugins, we will probably deprecate the old PaymentPlugin flow.

---

It is mandatory to include the manifest and `query` requirements for each webhook due to the following reasons:

- In the future, only GraphQL subscriptions will be used.
- Webhooks with a `query` use the GraphQL Engine, which generates the payload in a more optimized manner than the old engine.
- In most cases, the amount of data sent in a subscription is much less than in the old static payload. This means that we only send the data that you need.

**Comment by binary-koan** [comment]
@korycins That sounds awesome, from that explanation it should basically solve every other issue I had with the payment flow as well! I'll try out transactions instead and see if I run into any issues

Based on that the rationale for requiring `query` completely makes sense, I'll close this issue
