### ISSUE TITLE
Bug: draft order API doesn't validate provided shipping method

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#12712]
### What are you trying to achieve?

I want to be sure that the shipping method data stored in a draft order is valid.

### Steps to reproduce the problem

First scenario:
1. Create a draft order and provide a shipping method ID that doesn't belong to the `Order.shippingMethods` list of valid methods for this order.
2. Draft order is saved.
3. Problem - when only the channel and shipping address are known, the list of shipping methods is still empty (shipping is not required at this point, so we don't return any available methods). Products need to be set first to get the available options. Should we run validation only if the products and shipping addresses are known?

Second scenario:
1. Create a draft order and provide a valid shipping method, address, and products.
2. Change the shipping address to another country where this shipping method is not applicable.
3. Shipping method should be removed from the draft order.

### What did you expect to happen?

- Draft order API should validate provided shipping method IDs.
- It should clear the shipping method, shipping method name, and shipping tax rate when the method becomes invalid.
- Shipping tax rate should remain `null` when shipping method is not yet set.

### Environment

Saleor version: 3.9

**Comment by jakubkuc** [comment]
Further investigation and discussion revealed some new conclusions for this bug. 

Problems:
1.  The main problem is that `draftOrderUpdate` mutation does not update shipping data for order ( `shippingPrice`, `shippingTax`, `shippingMethodName`) when `shippingMethod` is provided in input. Which causes invalid data in draft order. 

Expected behavior:

1. Using draftOrderUpdate for updating shipping method should update all order fields connected to shipping ( `shippingPrice`, `shippingTax`, `shippingMethodName`, `shippingTaxClass`) 
2. We do not want to validate or remove shipping method when shippingAddress changes and shippingMethod becomes invalid - this would change flexibility in draftOrders (e.g. creating draft order with address and shipping method but without any lines would not be possible)

**Comment by maarcingebala** [comment]
Fixed in https://github.com/saleor/saleor/pull/13103.
