### ISSUE TITLE
Introduce `PUBLIC_URL` environment variable to set Saleor's domain

### ISSUE THREAD

**Issue by przlada** [saleor/saleor#12748]
## Problem

For Saleor to properly generate URLs pointing to itself, it needs to know the actual domain at which it is hosted. @patrys proposed the solution composed of:
- Introducing the `API_URL` environment variable, which could be set, for example, to `https://api.example.com/` 
- Deprecating the `shopDomainUpdate` mutation

This should resolve the issues listed below and mitigate similar ones in the future:
- https://github.com/saleor/saleor/issues/11267
- https://github.com/saleor/saleor/issues/12288
- https://github.com/saleor/saleor/discussions/11117

**Comment by lkostrowski** [comment]
I'd consider `PUBLIC_URL`, which is more explicit, especially since `API` sounds a little like "external API" while its about "own service"

More context from Apps perspective:

Apps during installation require Saleor API URL to be provided (in the request header). The app is using URL and token to check several things related mainly to security. Saleor Cloud has this URL set properly, but self hosted is using some default/fallback value (localhost) instead public URL. This results in failed app installation

**Comment by patrys** [comment]
Agreed, `PUBLIC_URL` sounds better. It's how the rest of the world can reach Saleor. It's not necessarily the hostname of the machine running Saleor, as you can have load balancers and reverse proxies in front of the actual service.
