### ISSUE TITLE
Add suport for unhandled field `trackInventoryByDefault`

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13492]
The `Shop` type defines the field `trackInventoryByDefault`, which is also available in the `ShopSettingsInput` input, but it's not used in the code anywhere. Most likely the field was added a long time ago in one of the first versions of API and removed before we started properly using field deprecation. It sounds useful, however, to have a field that would be used as a default value for `ProductVariant.trackInventory`.

TODO:
- Add logic that would use the `Shop.trackInventoryByDefault` value (if it is set) to populate `trackInventory` value (if not provided) in the following mutations:
  - `productVariantCreate`
  - `productVariantBulkCreate`
- Add a description to `Shop.trackInventoryByDefault` explaining that this field is used as a default value for ProductVariant.trackInventory
- Extend the description of all `trackInventory` fields to mention that if the field is not provided, `Shop.trackInventoryByDefault` would be used.

**Comment by Smit-Parmar** [comment]
@maarcingebala do we need to use ` Shop.trackInventoryByDefault` in update operations? 
let's say we have scenario were Product variant created using `productVariantCreate` and passed `trackInventory` as `false` but `Shop.trackInventoryByDefault` is `true` and while making doing `productVariantUpdate ` user has not passed any arguments like `trackInventory` so code will automatically pick the `Shop.trackInventoryByDefault` and mark that field as `true` that does not make any sense because user don't want to update that field.

**Comment by maarcingebala** [comment]
@Smit-Parmar Yes, it should work as you described, so only when the user is creating a variant and has not provided the `trackInventory` in the input, we should use the value from `Shop.trackInventoryByDefault`. We can skip populating that field in update operations as it might be unexpected for the user. I've updated the description; thanks!
