### ISSUE TITLE
[RFC] Add `externalId` field for a webhook

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#13656]
## Problem

Apps must manage webhooks lifecycle to keep them up to date, enable and disable them etc.

Currently app can find webhook with following methods:
1. Use a `name` field and store it in the code. Then query all webhooks and find by this name. It requires finding all webhooks in the app and name can be mutated, which will break the app
2. Rely on ID Saleor creates for webhook. App must query all webhooks, save their ID for the future in some database. For serverless apps its difficult and there is no "post install" event yet.
3. App can assume there is only once webhook per event and use event type

This is not perfect. 

The goal is to allow app to set its own ID in webhook manifest which will be persistent in Webhook in Saleor

---

## 1. General Assumptions

Add `externalID` that app can optionally register when webhook is created and when app is installed via manifest.

### Acceptance Criteria

- webhook can be queries via Saleor ID and external ID
- externalID is unique within app scope
- adding new external ID should 409 if already exist

### Questions
- should external ID be mutable via updateWebhook?

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by przlada** [comment]
1. Adding an `externalId` for webhook management is a promising move. While we could possibly make do with the `name` field, the `externalId` offers a more suitable and streamlined approach. It's essential that the `updateWebhook` mutation be permitted to set this `externalId`. This ensures that apps already in operation can leverage its benefits. Nonetheless, we should consider restricting staff users from modifying the `externalId`. This avoids complications, such as unintended changes to the `externalId` value, not done by the app, similar to the current potential with the `name` field.
2. We're in the process of rolling out a new mutation designed to upgrade apps based on their latest manifest, which we're currently calling `appUpgrade`. For this upgrade mechanism to be efficient, especially in terms of webhook configuration updates, there needs to be more than just relying on the `name` field. That's why adding the `externalId` is so important. Implementing this now offers immediate advantages and sets us up nicely for future requirements.

**Comment by krzysztofwolski** [comment]
My suggestion is to use name `slug` instead of `externalId` - IMO thats more consistent with the rest of the API.

Re restriction on changing the slug - IMO that's not required. Staff users can already break webhooks by changing metadata, target URL or events, etc.. I would follow the usual requirements for the slug - it has to be unique.

**Comment by lkostrowski** [comment]
https://linear.app/saleor/issue/IFREQ-23/add-externalid-field-for-registered-webhooks
