### ISSUE TITLE
Bug: Order expire&delete don't take into account TransactionItems

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14352]
What are you trying to achieve?
Current order expiration (channel.orderSettings.expireOrdersAfter) will expire orders only when they don't have any TransactionItem attached.

Steps to reproduce the problem
Allow to create unpaid orders (Channel.orderSettings.allowUnpaidOrders)
Call transactionInitialize mutation for PaymentApp. The returned result of the action should be CHARGE_ACTION_REQUIRED, CHARGE_FAILURE, AUTHORIZATION_FAILURE, AUTHORIZATION_ACTION_REQUIRED. All of them means, that processing payment is not finalized or failed.
Create unpaid order via checkoutComplete
Order is not paid but it will not expire and it will not be deleted as transactionItems are assigned to it.
What did you expect to happen?
I expect that the logic for expire and delete orders will take into account, that the order can have multiple unpaid transactionItems assigned to the order.
In that case "unpaid transaction item" means a transactiontransactionItem without any successful or pending [events](https://docs.saleor.io/docs/3.x/developer/payments#event-types-explanation).

Environment
Saleor version: 3.14+
OS and version: n/a

TODO
Investigate if Adyen sets XX_FAILURE even after user abandons payment session (e.g. redirect) and how long it takes.
Is the "timeout" configurable on Adyen side? If so we should probably sync it with channel's order expiration timeout.

**Comment by korycins** [comment]
To provide here more context. Unpaid orders can be created via public API (if enabled for specific channel). 
The unpaid order has status `unconfirmed`. When order doesn't receive new payment via transactionAPI in specific period of time (provided for a channel), it will be marked as expired. After X days, the order will be fully deleted (when X is a value provided for channel from 1 to 120 days). 
Currently logic for expiring and deleting orders assumes that unpaid order is an order without any transactionItems and without any Payment object. This assumption was valid previously. Since we allow to create new transactionItems via public API, there is a possibility that we will have unpaid orders with transaction items assigned to it. It means the mentioned logic will not take into account such orders.

---

Order stores the values like `totalCharged` and `totalAuthorized`. Both of them are denormalized values. They are the sum of charged, authorized amounts, calculated from all transactionItems assigned to the order. We could have the same fields for pending values (authorizePendingAmout, chargePendingAmount). This would simplify the logic for expire, delete, as we could use these fields to fetch the orders to expire and delete.

**Comment by witoszekdev** [comment]
Migrated, in progress: https://linear.app/saleor/issue/SHOPX-111/bug-order-expireanddelete-dont-take-into-account-transactionitems
