### ISSUE TITLE
Improve creation of promotion rule - variant relation

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#15145]
Refactor `fetch_variants_for_promotion_rules`.
We shouldn't delete and create a new one `PromotionRuleVariant` each time the method is called. Instead, we should check if something has changed, remove non-valid relations, and create new ones if any appear.
[Here](https://github.com/saleor/saleor/blob/main/saleor/product/utils/variants.py#L73) is the part that needs refactoring.

**Comment by maarcingebala** [comment]
As part of this task, we should estimate whether the `discount_promotionrule_variants.id` field needs to be an `integer` or `bigint` type in Postgres. We changed it to `bigint` in one of the deployments, as the limit of regular integer was exceeded due to many inserts to that table. We should answer these questions: 
- how many rules vs how many variants can be supported if we used integer type
- decide whether there should be any API limits for the number of supported variants/rules
- decide whether we should change this field to `bigint` in code, and create a migration for that
