### ISSUE TITLE
Bug: Async events triggered by the mutation have their payloads calculated synchronously

### ISSUE THREAD

**Issue by dnplkndll** [saleor/saleor#16750]
### What are you trying to achieve?

reasonable cloud performance on the premium supported cloud subscription

### Steps to reproduce the problem

add to cart takes more tan 10 seconds

### What did you expect to happen?

add to cart takes less than 1 second. 

### Logs

@JannikZed can you help with some logs?

### Environment

Saleor version: cloud?
OS and version: …

**Comment by mirekm** [comment]
Thank you for the report, @dnplkndll. We're actively addressing the issue. The complexity stems from external synchronous webhooks, but our team is working on both a resolution and mitigations.

**Comment by patrys** [comment]
We've identified that this is caused by events triggered by the mutation having their payloads calculated synchronously by the mutation code instead of delegating that work to a background task.

In this specific case, a fairly benign mutation triggers multiple `CHECKOUT_UPDATED` events, one of which causes taxes to be recalculated (an external HTTP call), which has a chance of causing the shipping price to be revalidated (another external HTTP call). Each of those inefficiencies seems innocent until they are all combined, and the mutation is blocked by numerous synchronous HTTP calls, which—added up—explain the observed delay.

We agree it's a significant problem, and we're addressing this by moving checkout-related asynchronous event triggers to background tasks.

**Comment by maarcingebala** [comment]
Delivered to 3.20 in [this PR](https://github.com/saleor/saleor/pull/16808), will be ported as well to main.
