### ISSUE TITLE
Bug: Voucher not accessible in Checkout

### ISSUE THREAD

**Issue by supersilverlemonhaze** [saleor/saleor#16767]
### What are you trying to achieve?

When i apply a voucher to a checkout i expect to be able to get some basic infos out of it, such as its name.

When a voucher is applied to a checkout, the field voucher is not accessible to non-staff users.

Only the voucher code is visible, however the voucher name is also important. Add this please. Thats all ty

### Steps to reproduce the problem

Read above

### What did you expect to happen?

Read above

### Logs

Read above

### Environment

Saleor version: …
OS and version: …
Read above

**Comment by aniav** [comment]
Hey @supersilverlemonhaze the voucher details, especially it's name is a internal detail available to staff users. It is intentional that customers going through checkout are not able to see such details as the company creating vouchers will use internal naming that can expose business details.

We will not be adding the expected change any time soon. I hope you are able to achieve what you are working with through the APIs we already provide. Thank you!
