### ISSUE TITLE
Backorder and pre-order support

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#4190]
### What I'm trying to achieve
Sometimes you want to keep track of the inventory numbers but want to allow customers to order products that are out-of-stock.

### Describe a proposed solution
Products (or variants, TBD) should have an option to allow purchases to be made while out of stock. The API would need to expose the information and the UI would need to reflect the product being out-of-stock.

Additional features (could be added later):
* Allow the store owner to set a threshold that (if set) would limit the total volume of preorders for a particular variant (eg. limit `quantity_allocated` to `quantity` + the threshold).

**Comment by auvipy** [comment]
anyone handling this?

**Comment by Loxon7** [comment]
this would be very useful!

**Comment by rrustvold** [comment]
I see this has been tagged as "backlog", but my usage of Saleor requires a backorder feature so I'm attempting to build it into my fork with the hopes of upstreaming it. I've noticed some oddities in how allocations work that I thought I would jot down here in case anyone has any thoughts. 

When orders are created, the api automatically creates allocations for the orderline, but it creates them from arbitrary warehouse stocks. That is, it loops over warehouses in no particular order and creates the allocations it needs. Even though fulfilling an order doesn't have to be done through the warehouse that the allocation was created from. Presumably this is only because an allocation is linked to a Stock entry which is linked to a warehouse. In other words, allocations are connected to warehouses even though they don't need to be.

My first idea for how to support a backorder would be to just create an allocation for for an order even if there doesn't exist enough stock for an item in warehouses. But if there is no stock at any warehouse, then you have no way to create an allocation at all. So instead I'm thinking it is probably better to track backorders in their own table, rather than as a special kind of allocation. This has other advantages like being able to query for backorders explicitly.

Another issue arises when stock at a warehouse is reduced through the dashboard. It is possible for inventory to be reduced to less than the total allocated amount. So essentially it's already possible to "backorder" products by removing inventory after allocating it to orders. However this puts the database into a bit of a confusing state since now there will exist allocations to stocks that can't cover the allocations. And until you go in to try to create fulfillments you won't even know that something is backordered.  I'm assuming this is an oversight in how Stock and Allocations are designed. Because it should definitely be possible to change the inventory level like this without any validation errors, but I think it might be best to convert un-covered allocations into backorder objects when this happens.

**Comment by maarcingebala** [comment]
This is not on the roadmap anymore, let's reopen if we decide to get back to this.
