### ISSUE TITLE
Move query-specific errors outside data in api response

### ISSUE THREAD

**Issue by jwm0** [saleor/saleor#4369]
### What I'm trying to achieve
While making queries/mutations wrapper for API, I want a universal way of handling errors in the application when user input is wrong. Currently the only way to display validation response from backend, is to put it inside query and then when response is OK - look at keys in result and get errors as previously defined in query (nested inside). This will bypass the default error handling mechanism in GraphQL. This also means that by using the default Apollo configuration, it will not catch any errors and developer is forced to check the output data for errors key sitting inside.

### Describe a proposed solution
 Move all query/mutation specific errors to be returned in the response itself (adjacent to `data`). Errors should not be specified in the queries but instead be visible by default (when query fails). My proposed response scheme is following:
```
{
  data: {...},
  errors: { // errors key is only defined when there are errors present
    <mutationName>: Array // as previously done
  }
}
```

This also seems to be the general consensus of how these should be handled in GraphQL, as seen here:
https://www.howtographql.com/graphql-python/6-error-handling/

If we were to go this direction, it's crucial we still allow to query for errors using the "old" way, as this would be a breaking change for any front-end API response error handling. So it makes sense to support both for some time.

### Useful links
https://blog.apollographql.com/full-stack-error-handling-with-graphql-apollo-5c12da407210 (example using Apollo-Server 2)
https://docs.graphene-python.org/projects/django/en/latest/mutations/#form-validation

**Comment by dominik-zeglen** [comment]
Those are not query errors but form errors. Different layer of abstraction.

**Comment by patrys** [comment]
The shape of `errors` field in the response is part of the standard and not something we can change: https://graphql.github.io/graphql-spec/June2018/#sec-Errors

**Comment by jwm0** [comment]
@dominik-zeglen These are user input errors in general but mostly form connected. I see Apollo Server 2+ gives methods that allow throwing errors to default GraphQL error mechanism, so maybe the library we are using (Graphene) providers a similar approach

@patrys fair enough, how about using extensions? I see that's what apollo server is using

**Comment by rafalp** [comment]
As mentioned by @patrys, shape of `results.errors` is something described by spec. It's possible to extend those with additional information, and I know that Apollo server mentions this and even [ships with few pre-made exceptions](https://www.apollographql.com/docs/apollo-server/features/errors/#codes) that cause additional data to appear on those - but trying to cram extra error details into `result.errors` results in increasing complexity on backend and frontend, and also cuts you off from some interesting features that `apollo-client` provides, like reverting optimistic update because mutation's "failed" payload contained object without the changes - approach we are documenting in [Ariadne's "Error messaging" docs]()https://ariadnegraphql.org/docs/error-messaging.

**Comment by patrys** [comment]
I guess we could use the protocol-level error field through the extensions mechanism to do something like:
```json
{
    "errors": [
        {
            "message": "Mutation failed",
            "path": ["fooBarBaz"],
            "locations": [],
            "extensions": {
                "userErrors": {
                    "email": [
                        "INVALID"
                    ],
                    "firstName": [
                        "REQUIRED"
                    ]
                }
            }
        }
    ]
}
```

This would have the added benefit of the client being aware of the mutation failing.

**Comment by jwm0** [comment]
@patrys this is what I had in mind, I like this approach for the ability to catch whenever a query fails - no matter what caused it, as that can be then read from the response itself. It also means the error field response type is a constant throughout the api and does not need to be specified on front-end when making queries.

@rafalp I think the overhead is not significant when implementing this, once done right from the beginning - the error handling should be easier to use on front-end. When data is not `null` I usually expect the query to be successful (or at least partially successful when making multiple queries) without the need to check for errors present. I digged through Apollo docs and I couldn't see any mentions where using error extensions for user input errors would cut some functionality away. Can you provide an example?

**Comment by patrys** [comment]
@jwm0 We can't assume that data being present means success. Partial successes are useful. Imagine a situation where a payment mutation fails but you still want to send the (failed) payment object to the client.

**Comment by jwm0** [comment]
@patrys true, but for specific cases like these - where failed request returns meaningful data we could use a solution similar to what we currently use (`success: boolean` flag inside query, or similar). I would imagine we only throw errors (and thus nullify data) for queries that output value solely depends on the input to be correct.

**Comment by maarcingebala** [comment]
We discussed with @patrys and @jwm0 and here is what we agreed on needs to be changed in our error handling.

1. Extend the `Error` type with the `code` enum field. These codes need to be precise, so each particular error where validation fails due to some business logic needs to have its unique code. Work on this one has already started in PR #4676.

2. Introduce error types specific to operations e.g. `CheckoutError` to handle only errors that can occur during the checkout process. A benefit of that is having enums for error codes related to one type of operations. E.g. `CheckoutErrorCode` would contain only error codes that can occur in checkout operations.
3. In the `Error` type change `field: String` to `field: [String!]` to be able to determine which input field caused the error, e.g. precisely:

```
{
  "data": {
    "staffCreate": {
      "user": null
    }
    "errors": [
      {
        "message": "User with this email already exists.",
        "code": "ALREADY_EXISTS"
        "field": ["input", "email"]
      }
    ]
  }
}
```

4. Move permission errors from the `errors` map (protocol errors). Instead, when a permission error occurs, we should return `null` for the field that the user has no access to. In mutation, we should return an error using the same mechanism as we use for validation errors.

Because most of those changes affect entire API and already existing clients we can start with changing it module by module. I would suggest starting with checkout API.

**Comment by Kwaidan00** [comment]
@maarcingebala would you like that I would refactor my PR regardless to adding `CheckoutErrorCode` and so on? Or should it stay and will be later refactored?

The second thing I thought - what would you think about adding `params` field to the message? When I worked with my PR, I've found a lot error messages like ` "Cannot add more than %d times this item." % settings.MAX_CHECKOUT_LINE_QUANTITY`. Without params (max quantity in that case) frontend can not provide valid error message in different language.

**Comment by maarcingebala** [comment]
This is partially solved since we have code names and specific error types for some of the mutation. We will have to figure out changing the `field` field from a string to a list of strings.

**Comment by peelar** [comment]
@maarcingebala Does it still qualify as "partially solved" or have we made some more progress on the topic? If not, I will keep it.

**Comment by maarcingebala** [comment]
We use dedicated error types for all new mutations, which fulfills point 2. Also, we add more context to mutation errors, for example, by allowing to query IDs of input items that cause the error.

**Comment by maarcingebala** [comment]
Closing this, as most of the topics mentioned here are already applied for new APIs.
