### ISSUE TITLE
Empty list in filters shouldn't be treated as null values

### ISSUE THREAD

**Issue by dominik-zeglen** [saleor/saleor#4690]
### What I'm trying to achieve
To filter with empty list of specifiers.

### Steps to reproduce the problem
1. 
```graphql
attributes(first: 5, filters: { ids: [] }) {
  edges {
    node {
      id
    }
  }
}
```

### What I expected to happen
Definitely not to omit filter. It should return empty list.

**Comment by NyanKiyoshi** [comment]
As well, `null` should keep its behavior, so returning "something".

**Comment by koradon** [comment]
The problem with this one is that `django-filters` is treating empty values as a skipped filter.
[docs](https://django-filter.readthedocs.io/en/master/guide/tips.html#filtering-by-an-empty-string)

We could work around it by adding the `MAGIC` value that indicates that filter should be applied in this case.

Any thoughts?

**Comment by korycins** [comment]
Why can't you change a definition of filter fields and their `filter` methods?
From the example above. `ids` filter is an instance of `GlobalIDMultipleChoiceFilter`. You can extend the current implementation to handle the given case.

**Comment by koradon** [comment]
That was my first attempt.
Unfortunately in the filter, I will get `value = []` either when the `ids` will be skipped in the query or set to `id: []`. So I can't distinct if this was intentional or not.
Changing it to return empty queryset on `[]` will work globally and will basically make that field required in query filters to have any result.
