### ISSUE TITLE
Seperate permission for Warehouse / Stocks

### ISSUE THREAD

**Issue by piotrantosz** [saleor/saleor#5213]
### What I'm trying to achieve
Seperate permissions for resolving warehouse/stocks, as usually different teams in company are responsible for managing orders and stock / inventory

### Describe a proposed solution
New permission

### Other solutions I've tried and won't work
…

**Comment by maarcingebala** [comment]
Managing stock quantities used to be part of the `ProductVariant` model. Before introducing warehouses, only `MANAGE_PRODUCTS` was required to manage inventory. Since stock quantity fields were moved to the `Stock` model, we wanted to keep the same permissions. I would say the question is about the `Warehouse` model since warehouses are related to shipping zones that have their own permission.

**Comment by Boquete** [comment]
@maarcingebala  is there any docs about creating new permissions for saleor based on django permissions? It's kinda complicated and some additional info would be great

**Comment by maarcingebala** [comment]
Unfortunately, there are no docs for that currently. To add new permission you have to:
- Add a new enum (or extend existing one) in `saleor/core/permissions.py`. Permissions are grouped into enums for each Django app or specific models if it makes sense.
- Make sure that your enum is added to `PERMISSIONS_ENUMS` in the same file.
- Add the permission in `class Meta` of a related model
- Generate new migrations and apply them to create permission in DB.

**Comment by maarcingebala** [comment]
After discussion, we agreed we should introduce separate permission for warehouses (`MANAGAE_WAREHOUSES`). Not sure though if the `Stock` model should also have its own permission or use the warehouses permission.
