### ISSUE TITLE
Extract Mutation logic like ModelMutation to an external package

### ISSUE THREAD

**Issue by ramzitannous** [saleor/saleor#7250]
### Extract Core Mutation logic to external package
Create a new package with ModelMutation and all the validations there.

**Comment by krzysztofwolski** [comment]
@ramzitannous Could you tell us more about this idea?

**Comment by onecrayon** [comment]
We have a similar need. In our particular instance, we are trying to add new models that track internal-specific data (for instance, a "business partner" model that connects Saleor users with our pre-existing systems). These models are not generic and would make no sense to contribute upstream, and currently there's not any good way to add the mutations for these encapsulated within a Django application package. The models and related database mutations are defined there, but to hook into GraphQL the only good option we could find was to modify the code within the `saleor` application directly, which is not very portable (it's already causing us minor headaches as we merge upstream changes from 3.0 into our internal fork).

Being able to better encapsulate GraphQL mutations and other schema within a Django app would be far preferable, because then we would only need to add our application to the `settings.py` file.

**Comment by onecrayon** [comment]
This is a feature request, and is not stale.

**Comment by maarcingebala** [comment]
I agree it would be useful to have the core classes separated, but currently, it doesn't align with our roadmap. We are focused on improving communication between Saleor and external services via webhooks and GraphQL API, as this is the recommended way of integration. Realistically, I doubt that the core team would have the capacity to work on this and maintain an additional library. In the future, we may be also looking at migrating away from Graphene and especially graphene-django, as there seems to be an issue with a lack of active maintainers.

**Comment by onecrayon** [comment]
> We are focused on improving communication between Saleor and external services via webhooks and GraphQL API, as this is the recommended way of integration.

For sure, and I wholly support this. As I understand this issue, the problem is that when a plugin adds a model to the database, the GraphQL endpoints are not capable of performing CRUD operations on that model, and the only way to add that is to modify the Saleor core application. Ideally, it would be nice if there were a way to define plugin-specific mutations such that they can extend the GraphQL endpoint with further queries and mutations for custom models.

As a concrete example, we track "business partners" in our application, and different business partners have different things they can do. Most of this lives comfortably in a custom plug-in, but all GraphQL mutations related to business partners are polluting the core Saleor project, which is non-ideal but we were unable to come up with any particularly clever architectural workarounds.

**Comment by onecrayon** [comment]
Feature request.
