### ISSUE TITLE
draftOrderComplete removes voucher

### ISSUE THREAD

**Issue by DVSoftware** [saleor/saleor#7541]
### What I'm trying to achieve
Because we use our own payment flow, we can't use the checkoutComplete mutation, therefore we are creating a draft order with the voucher applied and then we use draftOrderComplete to convert it to the order. The converted order does not have the discount applied anymore.

### Steps to reproduce the problem
1. create draft order with voucher using draftOrderCreate
2. complete the order with draftOrderComplete

### What I expected to happen
Voucher should be applied to the order if it was applied on the draft order.

### Screenshots and logs

**System information**

Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [x] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by Sahibreyaz** [comment]
Just me

**Comment by eCzerniak** [comment]
Hi @DVSoftware so I tried to reproduce this issue and: 
1. I've created a `voucher` 
![image](https://user-images.githubusercontent.com/29308910/128477451-f05fb93d-515c-4361-861b-b3724d92eb1c.png)
2. Then I added this voucher to `draftOrder` with `variants` and `user`
![image](https://user-images.githubusercontent.com/29308910/128479705-26ee26e8-9128-45c9-89dc-c25036a28eb5.png)
3. .. and added `shippingMethod`
![image](https://user-images.githubusercontent.com/29308910/128479956-b0682fe2-4040-414d-b5cc-d4d78c3c469e.png)
4. I used draftOrderComplete to complete it 
![image](https://user-images.githubusercontent.com/29308910/128480166-cdc78cee-bc5b-4a6e-9523-f9e22792037f.png)
... and it is ok I can see that total amount is discounted 
![image](https://user-images.githubusercontent.com/29308910/128480473-509e075e-c3ea-4d8e-b48f-d3deae90aede.png)
`shippingMethod` = 71.64 $
`variants` = 17 $ 
`voucher` = 10 $ 
`total` = 71.64 + 17 - 10 = 78.64 $ 
Could you give me more information if this problem is still present?  :)
