### ISSUE TITLE
OrderLine `undiscounted_unit_price` includes discounts

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor#7706]
Similar to #7664 I am still working my way through the codebase as part of implementing surcharge support, and I ran across what appears to be another oddity.

In the `add_variant_to_order` utility function at https://github.com/mirumee/saleor/blob/master/saleor/order/utils.py#L336 the unit price is set to the price of the variant *including discounts*. Later in that same method ([line 361](https://github.com/mirumee/saleor/blob/master/saleor/order/utils.py#L361)), the tax rates are applied such that `unit_price.gross` is the unit price plus taxes and `unit_price.net` is the unit price from before. Then `line.undiscounted_unit_price` is set to the unit price.

If I'm reading this correctly, this means that the undiscounted price is actually the discounted price, inclusive of taxes (under `.gross`). Am I missing something, or is this a logical bug in the Saleor code?

**Comment by onecrayon** [comment]
Can someone from Mirumee please clarify what is going on here? I'm really struggling to figure out how to calculate (and recalculate) discounts and surcharges for orders and checkouts, since I'm not clear on what counts as a "discounted" item vs. a normal price. For instance, if there's a sale running on an item, is that price the "undiscounted" cost? In which case, what constitutes a "discounted" cost?

**Comment by karolkielecki** [comment]
@onecrayon Hi Ian, thanks for reporting! It seems like a bug. We'll take a look into this issue. If I have any news, I'll let you know.

**Comment by rswilem** [comment]
I can confirm this. You can make this visual by disabling automatic order confirmation.
Complete a checkout and let the system create the order. In this case, my product costs €47, without any discounts set up. The (unconfirmed) order is fully paid.

Note the €0,00 price in the screenshot below:
![Screenshot 2021-08-12 at 11 18 53](https://user-images.githubusercontent.com/18720368/129172768-11bf7950-28e5-4f2e-8e32-bf2cb9772f74.png)

GraphQL API:
Note `undiscountedUnitPrice` in the data below.

```json
"order": {
      "lines": [
        {
          "id": "T3JkZXJMaW5lOjg3",
          "productName": "Test",
          "unitPrice": {
            "net": {
              "amount": 43.12
            },
            "tax": {
              "amount": 3.88
            },
            "gross": {
              "amount": 47
            }
          },
          "totalPrice": {
            "net": {
              "amount": 43.12
            },
            "tax": {
              "amount": 3.88
            },
            "gross": {
              "amount": 47
            }
          },
          "undiscountedUnitPrice": {
            "net": {
              "amount": 0
            },
            "tax": {
              "amount": 0
            },
            "gross": {
              "amount": 0
            }
          },
          "unitDiscount": {
            "currency": "EUR",
            "amount": 0
          },
          "unitDiscountType": "FIXED",
          "unitDiscountValue": 0,
          "unitDiscountReason": null
        }
      ]
    }
```


Also, when actually adding or removing a discount when the order is in this unconfirmed stage, the price (right column) becomes €0,00. My guess is that this is because the discount (e.g. 10%) is calculated from the `undiscountedUnitPrice`, but this is zero (so 10% of 0,00 = 0,00).

**Comment by karolkielecki** [comment]
We've confirmed the bug. We'll fix it as soon as we can.

**Comment by TomSteer** [comment]
@karolkielecki Hi Karol, Do you have any updates on this issue and whether it will make it into a 3.0.0 beta soon? Thanks

**Comment by designagencytom** [comment]
@karolkielecki  Hi Karol, any progress on this please? 
We're currently experiencing this issues and it would be great to know if this will be patched soon. Thanks!

**Comment by karolkielecki** [comment]
@TomSteer @designagencytom Hi guys. We're currently fully booked with other bugs. There is no ETA for the fix. I'll keep you posted.

**Comment by korycins** [comment]
Hey,
The issue is solved by - https://github.com/saleor/saleor/pull/8793, https://github.com/saleor/saleor/pull/8821.

The response for order now has correct values in undiscounted fields:
```
{
	"data": {
		"order": {
			"errors": [],
			"lines": [
				{
					"id": "T3JkZXJMaW5lOjU4",
					"undiscountedUnitPrice": {
						"gross": {
							"amount": 5.0
						},
						"net": {
							"amount": 5.0
						}
					},
					"unitPrice": {
						"gross": {
							"amount": 3.0
						}
					},
					"totalPrice": {
						"gross": {
							"amount": 6.0
						},
						"net": {
							"amount": 6.0
						}
					}
				},
				{
					"id": "T3JkZXJMaW5lOjYw",
					"undiscountedUnitPrice": {
						"gross": {
							"amount": 5.0
						},
						"net": {
							"amount": 5.0
						}
					},
					"unitPrice": {
						"gross": {
							"amount": 3.0
						}
					},
					"totalPrice": {
						"gross": {
							"amount": 3.0
						},
						"net": {
							"amount": 3.0
						}
					}
				},
				{
					"id": "T3JkZXJMaW5lOjYx",
					"undiscountedUnitPrice": {
						"gross": {
							"amount": 7.0
						},
						"net": {
							"amount": 7.0
						}
					},
					"unitPrice": {
						"gross": {
							"amount": 4.2
						}
					},
					"totalPrice": {
						"gross": {
							"amount": 4.2
						},
						"net": {
							"amount": 4.2
						}
					}
				}
			]
		}
	}
}
```



The unconfirmed order shows a line unit prices as below:
![image](https://user-images.githubusercontent.com/23282005/150958172-bd30ff2a-51a1-4415-8977-be73977eb8dd.png)

![image](https://user-images.githubusercontent.com/23282005/150958213-773696e7-8427-486c-91db-cad066ba5c89.png)
