### ISSUE TITLE
Saleor 2.11 Vatlayer support

### ISSUE THREAD

**Issue by KrEnjuTSU** [saleor/saleor#8319]
### What I'm trying to achieve
I'm trying to configure vatlayer for saleor 2.11. the taxrate typename returned from vatlayer is different from enum TaxRateType in saleor. As a result, a mismatch is happening and the tax page for individual countries is not loading.

### Steps to reproduce the problem

1. Get a vatlayer account with apikey and add it to saleor.
2. Use the fetch taxes in the saleor dashboard

### What I expected to happen
On the taxes page for individual countries, I expect to see the different tax rates for different types.

### Screenshots and logs

Below is enum type supported by saleor

![slresp](https://user-images.githubusercontent.com/31346476/136294041-e6bd95e6-927c-414a-bec9-41cac2d91a0b.PNG)
Below is vatlayer response

![vlresp](https://user-images.githubusercontent.com/31346476/136294102-982424b9-bc57-437f-918e-d0cadd2e6c25.PNG)
Below is the mapping of enum type and vatlayer response

![slcltx](https://user-images.githubusercontent.com/31346476/136387285-f2598836-4714-4591-bc0b-2be21fb1d944.PNG)
Below is the result of above two not matching with each other...

![taxresp](https://user-images.githubusercontent.com/31346476/136294143-9e7b5005-5087-44f7-a1b2-1d14e551095c.PNG)

**System information**

Saleor version(Including Dashboard and Storefront):
- [ ] 2.11

Operating system:
- [ ] Windows

**Comment by korycins** [comment]
Hey, I believe the issue is on the Vatlayer side.  Previously they were returning a list of common tax groups which were shared between countries. They changed something a couple of months ago, after that the tax groups are not shared between countries which means that it is hard to handle taxes for multiple countries. I've tried to contact them but without any response. This is something that we fix in 3.0, but it is something like a workaround on our side, to work with Vatlayer after these changes. 
I would recommend migrating to 3.0 if you still have such a possibility. It is still in beta, but It has more features, better performance (as we focus on it hardly).
