### ISSUE TITLE
Initial build fails

### ISSUE THREAD

**Issue by dekoza** [saleor/saleor#9764]
### What I'm trying to achieve
I'm trying to test this platform as described in First Steps: https://saleor.io/open-source/

### Steps to reproduce the problem

1. Clone the repo: git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3
2. cd saleor-platform
3. docker-compose build

### What I expected to happen
Build normally

### Screenshots and logs

```
------                                                                                                             
 > [saleor-platform_react-storefront 8/9] RUN pnpm install:                                                        
#0 0.995 Progress: resolved 1, reused 0, downloaded 0, added 0                                                     
#0 1.997 Progress: resolved 46, reused 0, downloaded 43, added 0                                                   
#0 2.996 Progress: resolved 54, reused 0, downloaded 54, added 0                                                   
#0 3.997 Progress: resolved 67, reused 0, downloaded 67, added 0                                                   
#0 4.996 Progress: resolved 139, reused 0, downloaded 136, added 0                                                 
#0 5.997 Progress: resolved 282, reused 0, downloaded 267, added 0                                                 
#0 6.997 Progress: resolved 409, reused 0, downloaded 395, added 0                                                 
#0 7.997 Progress: resolved 566, reused 0, downloaded 547, added 0                                                 
#0 8.996 Progress: resolved 664, reused 0, downloaded 645, added 0                                                 
#0 9.997 Progress: resolved 731, reused 0, downloaded 718, added 0                                                 
#0 11.00 Progress: resolved 785, reused 0, downloaded 771, added 0
#0 12.00 Progress: resolved 822, reused 0, downloaded 808, added 0
#0 12.71 Packages: +817
#0 12.71 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#0 12.95 Packages are hard linked from the content-addressable store to the virtual store.
#0 12.95   Content-addressable store is at: /root/.local/share/pnpm/store/v3
#0 12.95   Virtual store is at:             node_modules/.pnpm
#0 13.00 Progress: resolved 826, reused 0, downloaded 814, added 90
#0 14.00 Progress: resolved 826, reused 0, downloaded 815, added 817, done
#0 14.12 .../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
#0 14.17 .../node_modules/core-js-pure postinstall: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#0 14.17 .../node_modules/core-js-pure postinstall: The project needs your help! Please consider supporting of core-js:
#0 14.17 .../node_modules/core-js-pure postinstall: > https://opencollective.com/core-js 
#0 14.17 .../node_modules/core-js-pure postinstall: > https://patreon.com/zloirock 
#0 14.17 .../node_modules/core-js-pure postinstall: > https://paypal.me/zloirock 
#0 14.17 .../node_modules/core-js-pure postinstall: > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 
#0 14.17 .../node_modules/core-js-pure postinstall: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#0 14.17 .../node_modules/core-js-pure postinstall: Done
#0 14.57 
#0 14.57 > react-storefront@0.1.0 prepare /app
#0 14.57 > husky install
#0 14.57 
#0 14.62 fatal: not a git repository (or any of the parent directories): .git
#0 14.62 
#0 14.62 dependencies:
#0 14.62 + @apollo/client 3.5.10
#0 14.62 + @formatjs/swc-plugin 1.4.0
#0 14.62 + @formatjs/ts-transformer 3.9.2
#0 14.62 + @graphql-codegen/typescript-apollo-client-helpers 2.1.15
#0 14.62 + @headlessui/react 1.5.0
#0 14.62 + @heroicons/react 1.0.5
#0 14.62 + @saleor/sdk 0.4.4
#0 14.62 + @stripe/react-stripe-js 1.7.0
#0 14.62 + @stripe/stripe-js 1.26.0
#0 14.62 + @tailwindcss/aspect-ratio 0.4.0
#0 14.62 + @tailwindcss/forms 0.5.0
#0 14.62 + @tailwindcss/typography 0.5.2
#0 14.62 + clsx 1.1.1
#0 14.62 + dotenv 16.0.0
#0 14.62 + dotenv-cli 5.1.0
#0 14.62 + editorjs-blocks-react-renderer 1.2.4
#0 14.62 + graphql 16.3.0
#0 14.62 + next 12.1.4
#0 14.62 + next-seo 5.3.0
#0 14.62 + next-sitemap 2.4.3
#0 14.62 + next-usequerystate 1.7.0
#0 14.62 + react 18.0.0
#0 14.62 + react-dom 18.0.0
#0 14.62 + react-intl 5.24.6
#0 14.62 + tailwind-scrollbar-hide 1.1.7
#0 14.62 
#0 14.62 devDependencies:
#0 14.62 + @formatjs/cli 4.8.2
#0 14.62 + @graphql-codegen/add 3.1.1
#0 14.62 + @graphql-codegen/cli 2.6.2
#0 14.62 + @graphql-codegen/introspection 2.1.1
#0 14.62 + @graphql-codegen/typescript 2.4.8
#0 14.62 + @graphql-codegen/typescript-operations 2.3.5
#0 14.62 + @graphql-codegen/typescript-react-apollo 3.2.11
#0 14.62 + @next/bundle-analyzer 12.1.4
#0 14.62 + @types/qs 6.9.7
#0 14.62 + @types/react 17.0.43
#0 14.62 + @typescript-eslint/eslint-plugin 5.17.0
#0 14.62 + @typescript-eslint/parser 5.17.0
#0 14.62 + autoprefixer 10.4.2
#0 14.62 + eslint 8.12.0
#0 14.62 + eslint-config-airbnb 19.0.4
#0 14.62 + eslint-config-next 12.1.0
#0 14.62 + eslint-config-prettier 8.4.0
#0 14.62 + eslint-plugin-formatjs 3.0.0
#0 14.62 + eslint-plugin-import 2.25.4
#0 14.62 + eslint-plugin-jsx-a11y 6.5.1
#0 14.62 + eslint-plugin-react 7.29.4
#0 14.62 + eslint-plugin-react-hooks 4.3.0
#0 14.62 + eslint-plugin-simple-import-sort 7.0.0
#0 14.62 + husky 7.0.4
#0 14.62 + pathpida 0.18.1
#0 14.62 + postcss 8.4.12
#0 14.62 + prettier 2.6.2
#0 14.62 + react-hook-form 7.29.0
#0 14.62 + react-use 17.3.2
#0 14.62 + tailwindcss 3.0.23
#0 14.62 + typescript 4.6.3
#0 14.62 
#0 14.62  ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
#0 14.62 
#0 14.62 .
#0 14.62 ├─┬ @graphql-codegen/typescript-react-apollo
#0 14.62 │ └── ✕ missing peer graphql-tag@^2.0.0
#0 14.62 ├─┬ @graphql-codegen/typescript
#0 14.62 │ └─┬ @graphql-codegen/visitor-plugin-common
#0 14.62 │   └─┬ @graphql-tools/relay-operation-optimizer
#0 14.62 │     └─┬ relay-compiler
#0 14.62 │       └── ✕ unmet peer graphql@^15.0.0: found 16.3.0
#0 14.62 ├─┬ @saleor/sdk
#0 14.62 │ ├── ✕ unmet peer graphql@^15.5.0: found 16.3.0
#0 14.62 │ └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
#0 14.62 ├─┬ react-use
#0 14.62 │ ├── ✕ unmet peer react@"^16.8.0  || ^17.0.0": found 18.0.0
#0 14.62 │ └── ✕ unmet peer react-dom@"^16.8.0  || ^17.0.0": found 18.0.0
#0 14.62 ├─┬ @apollo/client
#0 14.62 │ └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
#0 14.62 ├─┬ @stripe/react-stripe-js
#0 14.62 │ ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
#0 14.62 │ └── ✕ unmet peer react-dom@"^16.8.0 || ^17.0.0": found 18.0.0
#0 14.62 ├─┬ editorjs-blocks-react-renderer
#0 14.62 │ └─┬ html-react-parser
#0 14.62 │   └── ✕ unmet peer react@"0.14 || 15 || 16 || 17": found 18.0.0
#0 14.62 └─┬ react-intl
#0 14.62   └── ✕ unmet peer react@"^16.3.0 || 17": found 18.0.0
#0 14.62 Peer dependencies that should be installed:
#0 14.62   graphql-tag@^2.0.0
#0 14.62 
------
failed to solve: executor failed running [/bin/sh -c pnpm install]: exit code: 1

```

**System information**

Saleor version:
- [x] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by maximesimoncelli** [comment]
I've had the same problem, it would seem that a `npx pnpm update` in **react-storefront** solved it for me.

I'm pretty sure that's not the best way to fix it, but at least it builds now. I've not launched the project yet though, so take that with a pinch of salt since it could completely break the storefront.

**Comment by dekoza** [comment]
The solution is to pinpoint the version of pnpm in `react-storefront/Dockerfile.dev`:
```
RUN npm install -g pnpm@6.32.11
```

I'll close it here since there's already an issue in `react-storefront` repo with this solution.

**Comment by rinjInTokyo** [comment]
I met the same problem and solve it with editing package.json:
1. error message shows that [Peer dependencies that should be installed:graphql-tag@^2.0.0] so just add "graphql-tag": "^2.0.0" to "dependencies"
2. [✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0] so change react version to 17.0.0
3. try install again may be still error, just keep editing the dependencies version.........
4. I solve this problem by editing "graphql" : "15.7.2",  "react" : "17.0.2",  "react-dom": "17.0.2",    and adding "graphql-tag": "^2.0.0"
I have not experience at front end so not sure its a good way to solve this problem

**Comment by kofoednielsen** [comment]
I'm attempting a fresh install of saleor and ran into the same issue. Maybe leave the issue open until it's solved to a point where new users nolonger expirence this?

**Comment by buhosiliscodirococo** [comment]
I've been trying for months to at least try a local demo, but the docker error has me exhausted, I think I'll go to django oscar. I can not spend more months of my life on this, the error is everywhere and with different solutions. absolutely no security for a serious project.

**Comment by lkostrowski** [comment]
Connected
https://github.com/saleor/react-storefront/issues/275

**Comment by lkostrowski** [comment]
https://github.com/saleor/saleor-platform/pull/158 was merged, that means react-storefront was updated to newest version. It apply fix for pnpm issue.

To fix your existing setup, please update submodule `react-storefront`

Issue should be solved, so I close this one.

**Comment by erne15** [comment]
I have attempted  installing  of saleor both manually  and using docker but  ran into the same issue. 

<pre> [10/10] RUN pnpm turbo run build:
#15 3.137  WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
#15 3.801 • Packages in scope: @saleor/checkout-storefront, @saleor/ui-kit, checkout, checkout-common, env-vars, eslint-config-checkout, saleor-app-checkout, storefront, tsconfig
#15 3.801 • Running build in 9 packages
#15 3.801  INFO  • Remote caching disabled
#15 3.804 checkout-common:build: cache miss, executing 95e4cbd41e2f5133
#15 3.804 @saleor/ui-kit:build: cache miss, executing 49fa3b6b10489787
#15 4.639 checkout-common:build: 
#15 4.639 checkout-common:build: &gt; checkout-common@0.1.0 build /app/packages/checkout-common
#15 4.639 checkout-common:build: &gt; NODE_ENV=production rollup -c
#15 4.639 checkout-common:build: 
#15 4.642 @saleor/ui-kit:build: 
#15 4.642 @saleor/ui-kit:build: &gt; @saleor/ui-kit@0.0.0 build /app/packages/ui-kit
#15 4.642 @saleor/ui-kit:build: &gt; rollup -c
#15 4.643 @saleor/ui-kit:build: 
#15 15.47 @saleor/ui-kit:build: 
<font color="#06989A">#15 15.47 @saleor/ui-kit:build: </font><font color="#06989A"><b>src/index.ts</b></font><font color="#06989A"> → </font><font color="#06989A"><b>dist/cjs/index.js, dist/esm/index.js</b></font><font color="#06989A">...</font>
#15 15.59 checkout-common:build: 
<font color="#06989A">#15 15.59 checkout-common:build: </font><font color="#06989A"><b>src/index.ts</b></font><font color="#06989A"> → </font><font color="#06989A"><b>dist/esm/index.js, dist/cjs/index.js</b></font><font color="#06989A">...</font>
#15 31.18 checkout-common:build: <font color="#4E9A06">created </font><font color="#4E9A06"><b>dist/esm/index.js, dist/cjs/index.js</b></font><font color="#4E9A06"> in </font><font color="#4E9A06"><b>15.5s</b></font>
#15 31.18 checkout-common:build: 
<font color="#06989A">#15 31.18 checkout-common:build: </font><font color="#06989A"><b>./dist/esm/index.d.ts</b></font><font color="#06989A"> → </font><font color="#06989A"><b>dist/index.d.ts</b></font><font color="#06989A">...</font>
#15 31.38 checkout-common:build: <font color="#4E9A06">created </font><font color="#4E9A06"><b>dist/index.d.ts</b></font><font color="#4E9A06"> in </font><font color="#4E9A06"><b>201ms</b></font>
#15 45.55 @saleor/ui-kit:build: <font color="#4E9A06">created </font><font color="#4E9A06"><b>dist/cjs/index.js, dist/esm/index.js</b></font><font color="#4E9A06"> in </font><font color="#4E9A06"><b>30s</b></font>
#15 45.55 @saleor/ui-kit:build: 
<font color="#06989A">#15 45.55 @saleor/ui-kit:build: </font><font color="#06989A"><b>./dist/esm/index.d.ts</b></font><font color="#06989A"> → </font><font color="#06989A"><b>dist/index.d.ts</b></font><font color="#06989A">...</font>
#15 45.94 @saleor/ui-kit:build: <font color="#C4A000"><b>(!) Unresolved dependencies</b></font>
#15 45.94 @saleor/ui-kit:build: <font color="#555753">https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency</font>
#15 45.94 @saleor/ui-kit:build: <b>@lib/globalTypes</b> (imported by dist/esm/components/Checkbox/Checkbox.d.ts, dist/esm/components/Chip/Chip.d.ts, dist/esm/components/IconButton/IconButton.d.ts, dist/esm/components/InfoTip/InfoTip.d.ts, dist/esm/components/Radio/Radio.d.ts, dist/esm/components/Select/Select.d.ts, dist/esm/components/Switch/Switch.d.ts, dist/esm/components/TextInput/TextInput.d.ts)
#15 45.94 @saleor/ui-kit:build: <font color="#4E9A06">created </font><font color="#4E9A06"><b>dist/index.d.ts</b></font><font color="#4E9A06"> in </font><font color="#4E9A06"><b>387ms</b></font>
#15 46.14 storefront:build: cache miss, executing bbcc621e1bc58df1
#15 46.15 @saleor/checkout-storefront:build: cache miss, executing 2ccef0d48a80f627
#15 46.89 @saleor/checkout-storefront:build: 
#15 46.89 @saleor/checkout-storefront:build: &gt; @saleor/checkout-storefront@0.1.0 build /app/packages/checkout-storefront
#15 46.89 @saleor/checkout-storefront:build: &gt; NODE_ENV=production rollup -c
#15 46.89 @saleor/checkout-storefront:build: 
#15 46.90 storefront:build: 
#15 46.90 storefront:build: &gt; storefront@0.1.0 build /app/apps/storefront
#15 46.90 storefront:build: &gt; next build
#15 46.90 storefront:build: 
#15 52.32 storefront:build: info  - Loaded env from /app/apps/storefront/.env
#15 52.82 @saleor/checkout-storefront:build: 
<font color="#06989A">#15 52.82 @saleor/checkout-storefront:build: </font><font color="#06989A"><b>src/index.tsx</b></font><font color="#06989A"> → </font><font color="#06989A"><b>dist/esm/index.js</b></font><font color="#06989A">...</font>
#15 52.91 storefront:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
#15 52.91 storefront:build: This information is used to shape Next.js&apos; roadmap and prioritize features.
#15 52.91 storefront:build: You can learn more, including how to opt-out if you&apos;d not like to participate in this anonymous program, by visiting the following URL:
#15 52.91 storefront:build: https://nextjs.org/telemetry
#15 52.91 storefront:build: 
#15 53.61 storefront:build: info  - Linting and checking validity of types...
#15 127.6 storefront:build: 
#15 127.6 storefront:build: ./pages/[channel]/[locale]/account/orders/[token].tsx
#15 127.6 storefront:build: 28:25  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
#15 127.6 storefront:build: 
#15 127.6 storefront:build: ./pages/[channel]/[locale]/account/register.tsx
#15 127.6 storefront:build: 40:44  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
#15 127.6 storefront:build: 42:47  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
#15 127.6 storefront:build: 
#15 127.6 storefront:build: ./pages/_document.tsx
#15 127.6 storefront:build: 11:17  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
#15 127.6 storefront:build: 
#15 127.6 storefront:build: ./components/ProductCard/ProductCard.tsx
#15 127.6 storefront:build: 40:17  Warning: Image elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
#15 127.6 storefront:build: 
#15 127.6 storefront:build: ./components/productList/FilteredProductList/FilteredProductList.tsx
#15 127.6 storefront:build: 147:32  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
#15 127.6 storefront:build: 
#15 127.6 storefront:build: ./lib/product.ts
#15 127.6 storefront:build: 35:12  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
#15 127.6 storefront:build: 
#15 127.6 storefront:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
#15 127.6 storefront:build: info  - Creating an optimized production build...
#15 199.1 @saleor/checkout-storefront:build: <font color="#C4A000"><b>(!) Plugin typescript: @rollup/plugin-typescript: outputToFilesystem option is defaulting to true.</b></font>
#15 199.1 @saleor/checkout-storefront:build: <font color="#4E9A06">created </font><font color="#4E9A06"><b>dist/esm/index.js</b></font><font color="#4E9A06"> in </font><font color="#4E9A06"><b>2m 26.2s</b></font>
#15 199.1 @saleor/checkout-storefront:build: 
<font color="#06989A">#15 199.1 @saleor/checkout-storefront:build: </font><font color="#06989A"><b>./dist/esm/index.d.ts</b></font><font color="#06989A"> → </font><font color="#06989A"><b>dist/index.d.ts</b></font><font color="#06989A">...</font>
#15 199.3 @saleor/checkout-storefront:build: <font color="#C4A000"><b>(!) Unresolved dependencies</b></font>
#15 199.3 @saleor/checkout-storefront:build: <font color="#555753">https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency</font>
#15 199.3 @saleor/checkout-storefront:build: @/checkout-storefront/providers/App<b>ConfigProvider/types</b> (imported by dist/esm/pages/Root.d.ts)
#15 199.3 @saleor/checkout-storefront:build: <font color="#4E9A06">created </font><font color="#4E9A06"><b>dist/index.d.ts</b></font><font color="#4E9A06"> in </font><font color="#4E9A06"><b>210ms</b></font>
#15 199.9 saleor-app-checkout:build: cache miss, executing 0b325a84d29d9bbe
#15 199.9 checkout:build: cache miss, executing 76db862455e6d9a2
#15 202.7 saleor-app-checkout:build: 
#15 202.7 saleor-app-checkout:build: &gt; saleor-app-checkout@0.0.0 build /app/apps/saleor-app-checkout
#15 202.7 saleor-app-checkout:build: &gt; next lint --dir . --quiet &amp;&amp; npm run i18n &amp;&amp; next build
#15 202.7 saleor-app-checkout:build: 
#15 202.8 checkout:build: 
#15 202.8 checkout:build: &gt; checkout@0.1.0 build /app/apps/checkout
#15 202.8 checkout:build: &gt; react-scripts build
#15 202.8 checkout:build: 
#15 203.2 saleor-app-checkout:build: info  - Loaded env from /app/apps/saleor-app-checkout/.env
#15 210.2 saleor-app-checkout:build: warn  - You have enabled experimental features (esmExternals, externalDir) in next.config.js.
#15 210.2 saleor-app-checkout:build: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
#15 210.2 saleor-app-checkout:build: 
#15 227.8 checkout:build: Creating an optimized production build...
#15 238.8 storefront:build: info  - Compiled successfully
#15 238.8 storefront:build: info  - Collecting page data...
#15 259.0 storefront:build: info  - Generating static pages (0/11)
#15 260.8 storefront:build: info  - Generating static pages (2/11)
#15 260.9 storefront:build: info  - Generating static pages (5/11)
#15 261.0 storefront:build: info  - Generating static pages (8/11)
#15 261.1 storefront:build: info  - Generating static pages (11/11)
#15 261.2 storefront:build: info  - Finalizing page optimization...
#15 261.2 storefront:build: 
#15 261.5 storefront:build: Route (pages)                                   Size     First Load JS
#15 261.5 storefront:build: ┌ ○ /                                           238 B           175 kB
#15 261.5 storefront:build: ├   /_app                                       0 B             175 kB
#15 261.5 storefront:build: ├ ● /[channel]/[locale]                         509 B           263 kB
#15 261.5 storefront:build: ├ λ /[channel]/[locale]/[sitemap]               256 B           175 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/account/addressBook     624 B           263 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/account/login           1.33 kB         189 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/account/orders          660 B           263 kB
#15 261.5 storefront:build: ├ ● /[channel]/[locale]/account/orders/[token]  1.35 kB         264 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/account/preferences     1.62 kB         264 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/account/register        1.26 kB         189 kB
#15 261.5 storefront:build: ├ ● /[channel]/[locale]/category/[slug]         1.02 kB         269 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/checkout                638 B           263 kB
#15 261.5 storefront:build: ├ ● /[channel]/[locale]/collection/[slug]       904 B           269 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/order                   494 B           263 kB
#15 261.5 storefront:build: ├ ● /[channel]/[locale]/page/[slug]             955 B           264 kB
#15 261.5 storefront:build: ├ ● /[channel]/[locale]/products/[slug]         4.01 kB         267 kB
#15 261.5 storefront:build: ├ ○ /[channel]/[locale]/search                  1.64 kB         264 kB
#15 261.5 storefront:build: └ ○ /404 (1616 ms)                              766 B           197 kB
#15 261.5 storefront:build:     └ css/d671ab48dc86a1f9.css                  1.51 kB
#15 261.5 storefront:build: + First Load JS shared by all                   182 kB
#15 261.5 storefront:build:   ├ chunks/framework-ceb470d8f68752fc.js        45.5 kB
#15 261.5 storefront:build:   ├ chunks/main-2c4bd73a4a4b956c.js             35 kB
#15 261.5 storefront:build:   ├ chunks/pages/_app-f0878ee07f1c59cb.js       93.7 kB
#15 261.5 storefront:build:   ├ chunks/webpack-6ef43a8d4a395f49.js          999 B
#15 261.5 storefront:build:   └ css/12e26599b9ad2537.css                    7.24 kB
#15 261.5 storefront:build: 
#15 261.5 storefront:build: ƒ Middleware                                    21.8 kB
#15 261.5 storefront:build: 
#15 261.5 storefront:build: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
#15 261.5 storefront:build: ○  (Static)  automatically rendered as static HTML (uses no initial props)
#15 261.5 storefront:build: ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
#15 261.5 storefront:build: 
#15 319.1 saleor-app-checkout:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
#15 319.1 saleor-app-checkout:build: This information is used to shape Next.js&apos; roadmap and prioritize features.
#15 319.1 saleor-app-checkout:build: You can learn more, including how to opt-out if you&apos;d not like to participate in this anonymous program, by visiting the following URL:
#15 319.1 saleor-app-checkout:build: https://nextjs.org/telemetry
#15 319.1 saleor-app-checkout:build: 
#15 330.1 saleor-app-checkout:build: ✔ No ESLint warnings or errors
#15 335.2 saleor-app-checkout:build: 
#15 335.2 saleor-app-checkout:build: &gt; saleor-app-checkout@0.0.0 i18n
#15 335.2 saleor-app-checkout:build: &gt; npm run extract:i18n &amp;&amp; npm run compile:i18n
#15 335.2 saleor-app-checkout:build: 
#15 336.0 saleor-app-checkout:build: 
#15 336.0 saleor-app-checkout:build: &gt; saleor-app-checkout@0.0.0 extract:i18n
#15 336.0 saleor-app-checkout:build: &gt; formatjs extract &apos;{backend,config,content,frontend,graphql,pages,types,utils}/**/*.{js,jsx,ts,tsx}&apos; --format transifex --id-interpolation-pattern &apos;[folder]/[name]/[sha512:contenthash:base64:6]&apos; --out-file content/locales/en.json
#15 336.0 saleor-app-checkout:build: 
#15 352.4 checkout:build: The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
#15 353.1 checkout:build:  ELIFECYCLE  Command failed with exit code 1.
#15 353.3 checkout:build: ERROR: command finished with error: command (/app/apps/checkout) pnpm run build exited (1)
#15 353.8 
#15 353.8 command (/app/apps/checkout) pnpm run build exited (1)
#15 353.8  Tasks:    4 successful, 5 total
#15 353.8 Cached:    0 cached, 5 total
#15 353.8   Time:    5m50.769s 
#15 353.8 
#15 353.8  ERROR  run failed: command  exited (1)
------
executor failed running [/bin/sh -c pnpm turbo run build]: exit code: 1
<font color="#CC0000">ERROR</font>: Service &apos;saleor-app-checkout&apos; failed to build : Build failed</pre>

**Comment by erne15** [comment]
pnpm start

> saleor-storefront@0.0.0 start /home/ernest/projects/saleor/react-storefront
> env-cmd --no-override -f .env env-cmd --no-override -f .env.local --fallback turbo run start --parallel --cache-dir=.turbo

• Packages in scope: @saleor/checkout-storefront, @saleor/ui-kit, checkout, checkout-common, env-vars, eslint-config-checkout, saleor-app-checkout, storefront, tsconfig
• Running start in 9 packages
• Remote caching disabled
saleor-app-checkout:start: cache bypass, force executing 0423542fab5fbbe6
storefront:start: cache bypass, force executing 1131475e05358290
saleor-app-checkout:start: 
saleor-app-checkout:start: > saleor-app-checkout@0.0.0 start /home/ernest/projects/saleor/react-storefront/apps/saleor-app-checkout
saleor-app-checkout:start: > next start -p 3001
saleor-app-checkout:start: 
storefront:start: 
storefront:start: > storefront@0.1.0 start /home/ernest/projects/saleor/react-storefront/apps/storefront
storefront:start: > next start
storefront:start: 
saleor-app-checkout:start: ready - started server on 0.0.0.0:3001, url: http://localhost:3001
saleor-app-checkout:start: info  - Loaded env from /home/ernest/projects/saleor/react-storefront/apps/saleor-app-checkout/.env
storefront:start: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
storefront:start: info  - Loaded env from /home/ernest/projects/saleor/react-storefront/apps/storefront/.env
saleor-app-checkout:start: warn  - Invalid next.config.js options detected: 
storefront:start: Error: Could not find a production build in the '/home/ernest/projects/saleor/react-storefront/apps/storefront/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
storefront:start:     at NextNodeServer.getBuildId (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next-server.js:165:23)
storefront:start:     at new Server (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/base-server.js:56:29)
storefront:start:     at new NextNodeServer (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next-server.js:67:9)
storefront:start:     at NextServer.createServer (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next.js:144:16)
storefront:start:     at async /home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next.js:156:31
storefront:start:     at async NextServer.prepare (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next.js:131:24)
storefront:start:     at async /home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/cli/next-start.js:116:9
saleor-app-checkout:start:   - The root value has an unexpected property, sentry, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
saleor-app-checkout:start: 
saleor-app-checkout:start: See more info here: https://nextjs.org/docs/messages/invalid-next-config
saleor-app-checkout:start: warn  - You have enabled experimental features (esmExternals, externalDir) in next.config.js.
saleor-app-checkout:start: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
saleor-app-checkout:start: 
storefront:start:  ELIFECYCLE  Command failed with exit code 1.
storefront:start: ERROR: command finished with error: command (/home/ernest/projects/saleor/react-storefront/apps/storefront) pnpm run start exited (1)
saleor-app-checkout:start: Error: Could not find a production build in the '/home/ernest/projects/saleor/react-storefront/apps/saleor-app-checkout/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
saleor-app-checkout:start:     at NextNodeServer.getBuildId (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next-server.js:165:23)
saleor-app-checkout:start:     at new Server (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/base-server.js:56:29)
saleor-app-checkout:start:     at new NextNodeServer (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next-server.js:67:9)
saleor-app-checkout:start:     at NextServer.createServer (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next.js:144:16)
saleor-app-checkout:start:     at async /home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next.js:156:31
saleor-app-checkout:start:     at async NextServer.prepare (/home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/server/next.js:131:24)
saleor-app-checkout:start:     at async /home/ernest/projects/saleor/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.0_qtpcxnaaarbm4ws7ughq6oxfve/node_modules/next/dist/cli/next-start.js:116:9
command (/home/ernest/projects/saleor/react-storefront/apps/storefront) pnpm run start exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.385s 

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

i cant get the react store front working either by manual installing or docker kindly could you help
